### ISSUE TITLE
New Site health page fails to work

### ISSUE THREAD

**Issue by A-Matt** [ProjectNami/projectnami#348]
**Project Nami**: 2.2.0
**Wordpress version**: 5.2.0
**SQL Server**: 2017

Running the page `./wp-admin/site-health.php` 

Provides error
```
Fatal error: Uncaught Error: Call to undefined function mysql_get_server_info() in <FILE_LOCATION>\wp-admin\includes\class-wp-site-health.php:130
Stack trace:
#0 <FILE_LOCATION>\wp-admin\includes\class-wp-site-health.php(29): WP_Site_Health->prepare_sql_data()
#1 <FILE_LOCATION>\wp-admin\site-health.php(30): WP_Site_Health->__construct()
#2 {main} thrown in <FILE_LOCATION>\wp-admin\includes\class-wp-site-health.php on line 130
```

**Comment by benoithamet** [comment]
Well seems this page exists when an issue is detected with WP and/or plugins
Just got the page working after receiving a notification email because I have a plugin which is not quite well
Not sure if this was the intention (aka page only available if there is an issue detected)

**Comment by patrickebates** [comment]
As part of the latest update, a quick pass was made to simply disable the DB checks until a proper fix can be put into place.  Expect a warning that the DB version is out of date for now.

**Comment by benoithamet** [comment]
Hi Patrick
seems this is now resolved with the latest update; health page is loading properly
not sure if this "Severely outdated SQL server" is the warning your are talking about?
thanks

**Comment by patrickebates** [comment]
That's the one.  The calls WP is making to check DB settings have similar versions for SQLSrv object, but they return different data.  Until we can make full corrections, it thinks the DB version is zero and therefore out of date.

**Comment by benoithamet** [comment]
thanks
all good then
