### ISSUE TITLE
Woocommerce clean install failing status

### ISSUE THREAD

**Issue by IainESGlass** [ProjectNami/projectnami#388]
Latest Project Nami  Windows Server 2016  7.3 php  SQL Server 2016 Standard
Tried multiple clean installs with no other plugins
issues with assigning categories to items
you can only add one product to shopping cart
you cannot update nor delete the product in the cart
will checkout etc
Woocommerce status blows up with fatal error:

Fatal error: Uncaught Error: Call to undefined function mysql_get_server_info() in C:\inetpub\Ethical_WP\wp-content\plugins\woocommerce\includes\wc-core-functions.php:2277 Stack trace: #0 C:\inetpub\Ethical_WP\wp-content\plugins\woocommerce\packages\woocommerce-rest-api\src\Controllers\Version2\class-wc-rest-system-status-v2-controller.php(713): wc_get_server_database_version() #1 C:\inetpub\Ethical_WP\wp-content\plugins\woocommerce\packages\woocommerce-rest-api\src\Controllers\Version2\class-wc-rest-system-status-v2-controller.php(589): WC_REST_System_Status_V2_Controller->get_environment_info_per_fields(Array) #2 C:\inetpub\Ethical_WP\wp-content\plugins\woocommerce\packages\woocommerce-rest-api\src\Controllers\Version2\class-wc-rest-system-status-v2-controller.php(75): WC_REST_System_Status_V2_Controller->get_item_mappings_per_fields(Array) #3 C:\inetpub\Ethical_WP\wp-includes\rest-api\class-wp-rest-server.php(946): WC_REST_System_Status_V2_Controller->get_items(Object(WP_REST_Request)) #4 C:\inetpub\Ethical_WP\wp-inclu in C:\inetpub\Ethical_WP\wp-content\plugins\woocommerce\includes\wc-core-functions.php on line 2277

**Comment by patrickebates** [comment]
Woocommerce makes use of MySQL commands which have no equivalent in SQL Server, so it cannot be made to work correctly with PN.

**Comment by IainESGlass** [comment]
Disappointing.   It has built all its' tables etc within SQL.  No issues with it storing products, orders and much more processing.
So what ordering taking package(s) will work with ProjectNami

**Comment by patrickebates** [comment]
I took another look at the error above.  This isn't an issue with a MySQL command but rather the plugin attempting to access the PHP driver for MySQL directly.  Same end result in that it just won't work, though.

As for order handling plugins, I can't make any recommendations as I haven't tried to use any.
