### ISSUE TITLE
WP-mail new update crashed the site

### ISSUE THREAD

**Issue by slamsan** [ProjectNami/projectnami#403]
Hello, i'm new to GitHub from today because i need to ask what caused my site to crash.
I have the wp-mail plugin installed on my project nami site and everything was working totally clean and smooth, but the new wp-mail  update made it crash totally, I had to manually remove the wp-mail plugin folder to make the site alive again.
Running the site on windows 10 IIS with SQLExpress 2019 and all latest updates

I'm not into code and that stuff, but i can make changes to code  with som help, here is the error.
Best Regards
Lennart 

Fatal error: Uncaught RuntimeException: Error saving action: Error saving action: [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Unclosed quotation mark after the character string 'O:30:"ActionScheduler_SimpleSchedule":2:{s:22:"'. in C:\inetpub\wwwroot\S.O.C\wp-content\plugins\wp-mail-smtp\vendor\woocommerce\action-scheduler\classes\migration\ActionScheduler_DBStoreMigrator.php:44 Stack trace: #0 C:\inetpub\wwwroot\S.O.C\wp-content\plugins\wp-mail-smtp\vendor\woocommerce\action-scheduler\classes\data-stores\ActionScheduler_HybridStore.php(242): ActionScheduler_DBStoreMigrator->save_action() #1 C:\inetpub\wwwroot\S.O.C\wp-content\plugins\wp-mail-smtp\vendor\woocommerce\action-scheduler\classes\ActionScheduler_ActionFactory.php(177): ActionScheduler_HybridStore->save_action() #2 C:\inetpub\wwwroot\S.O.C\wp-content\plugins\wp-mail-smtp\vendor\woocommerce\action-scheduler\classes\ActionScheduler_ActionFactory.php(84): ActionScheduler_ActionFactory->store() #3 C:\inetpub\wwwroot\S.O.C\wp-content\plugins\wp-mail-smtp\ven in C:\inetpub\wwwroot\S.O.C\wp-content\plugins\wp-mail-smtp\vendor\woocommerce\action-scheduler\classes\migration\ActionScheduler_DBStoreMigrator.php on line 44

**Comment by kilasuit** [comment]
As this is a plugin issue you should check the plugin support forum - which looks like this has already been raised there as you can see at https://wordpress.org/support/topic/version-2-1-1-crashing-wp-admin/

There is what looks to be a fix there as well that you could give a try

**Comment by slamsan** [comment]
Oh, sorry for posting in the wrong place, I will check the link
Thank you very much, have a nice day
