### ISSUE TITLE
woocommerce 6.7.0 with Nami 3.0.1

### ISSUE THREAD

**Issue by WolvenRA** [ProjectNami/projectnami#478]
When trying to "Activate" woocommerce in WordPress I got the following Fatal error...  I thought you guys might like to know.

Fatal error: Uncaught RuntimeException: Error saving action: Error saving action: [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Unclosed quotation mark after the character string 'O:30:"ActionScheduler_SimpleSchedule":2:{s:22:"'. in C:\inetpub\wwwroot\wp-content\plugins\woocommerce\packages\action-scheduler\classes\migration\ActionScheduler_DBStoreMigrator.php:44 Stack trace: #0 C:\inetpub\wwwroot\wp-content\plugins\woocommerce\packages\action-scheduler\classes\data-stores\ActionScheduler_HybridStore.php(242): ActionScheduler_DBStoreMigrator->save_action() #1 C:\inetpub\wwwroot\wp-content\plugins\woocommerce\packages\action-scheduler\classes\ActionScheduler_ActionFactory.php(177): ActionScheduler_HybridStore->save_action() #2 C:\inetpub\wwwroot\wp-content\plugins\woocommerce\packages\action-scheduler\classes\ActionScheduler_ActionFactory.php(84): ActionScheduler_ActionFactory->store() #3 C:\inetpub\wwwroot\wp-content\plugins\woocommerce\packages\action-scheduler\functions.php(36): ActionScheduler_ActionFactory->si in C:\inetpub\wwwroot\wp-content\plugins\woocommerce\packages\action-scheduler\classes\migration\ActionScheduler_DBStoreMigrator.php on line 44

There has been a critical error on this website. Please check your site admin email inbox for instructions.

**Comment by patrickebates** [comment]
Please see https://projectnami.org/plugin-compatibility/

WooCommerce, which is specifically called out on that page, is a plugin which interfaces with the MySQL objects directly.  There's really not anything we can do to make it work.

**Comment by WolvenRA** [comment]
Thanx for responding Patrick,

	From your plugin compatibility page I found this… 

        "The fastest way to determine if a plugin is attempting direct database access?  Search within the plugin files for $wpdb as it should only be referenced with DB queries."  

I’m a computer programmer so I can modify the offending code, but the comment above doesn’t tell me what to do with the “$wpdb” when I find them.  Is there someplace that sets $wpdb to some value that I could change to MSSQL, or do I need to replace the “$wpdb” with something else?

Thanx,
Randy

**Comment by patrickebates** [comment]
It's not so much a matter of replacing $wpdb as it is modifying the queries to work with MSSQL.

The issue with WooCommerce is that it will bypass $wpdb and go directly to the PHP db objects themselves, which completely evades the translation layer in PN.

**Comment by WolvenRA** [comment]
Welll...  that's a PITA...  :)

**Comment by WolvenRA** [comment]
I guess I'll stick with version 6.1   At least it activated.  Whether it will actually work, I guess I'll find out.

**Comment by WolvenRA** [comment]
Turns out version 6.1 doesn't work either.  So I'm guessing that either I can't use woocommerce, or I can use Nami...  Right?

**Comment by patrickebates** [comment]
Pretty much.  Unfortunately, this is a problem with many "premium" plugins that decided to do their own thing rather than properly follow WP guidelines to use the DB API.  WooCommerce is actually owned by Automattic now, the creators of WordPress, so it's more than a bit ironic...
