### ISSUE TITLE
Manual deployment to App Service on Linux fails to work with error

### ISSUE THREAD

**Issue by MasayukiOzawa** [ProjectNami/projectnami#490]
With PHP 7.4 EOL imminent, we expect the App Service to use Linux in the future.
When I tried to deploy the App Service on Linux (PHP 8.1), I got the following error and could not run it.

```
2022-11-08T05:02:47.372064627Z: [ERROR]  127.0.0.1 -  08/Nov/2022:05:02:47 +0000 "GET /wp-admin/setup-config.php" 500
2022-11-08T05:02:47.372849065Z: [ERROR]  NOTICE: PHP message: PHP Fatal error:  Uncaught TypeError: sqlsrv_query(): Argument #1 ($conn) must be of type resource, null given in /home/site/wwwroot/wp-includes/wp-db.php:2110
2022-11-08T05:02:47.373366190Z: [ERROR]  Stack trace:
2022-11-08T05:02:47.374534346Z: [ERROR]  #0 /home/site/wwwroot/wp-includes/wp-db.php(2110): sqlsrv_query(NULL, 'SELECT option_v...')
2022-11-08T05:02:47.374552747Z: [ERROR]  #1 /home/site/wwwroot/wp-includes/wp-db.php(2694): wpdb->_do_query('SELECT option_v...')
2022-11-08T05:02:47.374560147Z: [ERROR]  #2 /home/site/wwwroot/wp-includes/functions.php(1785): wpdb->get_var('SELECT option_v...')
2022-11-08T05:02:47.374565448Z: [ERROR]  #3 /home/site/wwwroot/wp-includes/load.php(755): is_blog_installed()
2022-11-08T05:02:47.374570348Z: [ERROR]  #4 /home/site/wwwroot/wp-settings.php(159): wp_not_installed()
2022-11-08T05:02:47.374575548Z: [ERROR]  #5 /home/site/wwwroot/wp-admin/setup-config.php(33): require('/home/site/wwwr...')
2022-11-08T05:02:47.374580548Z: [ERROR]  #6 {main}
2022-11-08T05:02:47.374585349Z: [ERROR]    thrown in /home/site/wwwroot/wp-includes/wp-db.php on line 2110
```

Deployment to the App Service is done by deploying the latest branch of Nami's repository in the Deploye Center.
Do I need to do any additional configuration to get the App Service on Linux to work with the latest PHP?

**Comment by patrickebates** [comment]
It's been a while since I ran PN on Linux, but it was working fine before.  It was even part of the beta testing and demos of SQL Server on Linux years ago.

I'm not certain from the error if this is a problem with the connection string or the sqlsrv object.
This error occurred immediately after you provided the database parameters?

**Comment by MasayukiOzawa** [comment]
Thank you for your response.
I have not set any database parameters. The error occurs during initial setup on first access.
On the first access after deployment, I get an error after being redirected to "wp-admin/setup-config.php".

**Comment by patrickebates** [comment]
I see in your error above that the conn parameter is NULL.  I'm confused why it would be attempting a DB connection prior to settings being available.  I will try to duplicate tomorrow.

**Comment by MasayukiOzawa** [comment]
I changed to PHP 7.4 on App Service on Linux and it works.
It does not seem to work with PHP 8.0 and above.

**Comment by Husky-Devel** [comment]
> I changed to PHP 7.4 on App Service on Linux and it works. It does not seem to work with PHP 8.0 and above.

Good to know

**Comment by gabriel-alves-ivoryit** [comment]
Adding to the discussion, i'm also finding it impossible to run Project Nami on Linux Web Apps on Azure. I get 404 errors as soon as wp-config.php is in place (not before), even when accessing "/" (which redirected me  correctly to "/wp-admin/setup-config.php" before, indicating the cause is not really Nginx not finding the files). 

The Web App's log stream recorded the following:

```
2023-03-05T14:14:55.540718706Z: [ERROR]  NOTICE: PHP message: PHP Warning:  require_once(/home/site/wwwroot/wp-includes/load.php): Failed to open stream: No such file or directory in /home/site/wwwroot/wp-load.php on line 62
2023-03-05T14:14:55.540736407Z: [ERROR]  NOTICE: PHP message: PHP Fatal error:  Uncaught Error: Failed opening required '/home/site/wwwroot/wp-includes/load.php' (include_path='.:/usr/local/lib/php') in /home/site/wwwroot/wp-load.php:62
2023-03-05T14:14:55.540742207Z: [ERROR]  Stack trace:
2023-03-05T14:14:55.541438924Z: [ERROR]  #0 /home/site/wwwroot/wp-blog-header.php(13): require_once()
2023-03-05T14:14:55.541455324Z: [ERROR]  #1 /home/site/wwwroot/index.php(17): require('/home/site/wwwr...')
2023-03-05T14:14:55.541460224Z: [ERROR]  #2 {main}
2023-03-05T14:14:55.541464224Z: [ERROR]    thrown in /home/site/wwwroot/wp-load.php on line 62
```

**Comment by patrickebates** [comment]
I have been wondering if Nginx might be the wildcard here.  We only tested on Apache and Linux, and that was years ago.  But I have no idea why Nginx would dislike the files.

**Comment by MasayukiOzawa** [comment]
After checking that the current App Service on Linux could be deployed, the initial set-up was completed and progress was made up to the display of the administration page.

However, when I opened the top page or a post, the HTTP Status was 200, but it became WSoD and I could not display the post.

Has anyone been able to deploy with App Service on Linux?

**Comment by MasayukiOzawa** [comment]
Sorry. My settings were wrong.
App Service on Linux (PHP 8.2) and the basic parts seem to work.

**Comment by patrickebates** [comment]
I'm still learning on this myself, but had to support a couple of sites on Linux so far.  I had to create a custom config for Nginx and set a startup command on the App Service in the Azure portal to copy that config into the correct location and restart the service.
[default.txt](https://github.com/ProjectNami/projectnami/files/14119393/default.txt)

I've attached the file I used, though you will need to remove the .txt or update the startup command, which follows.

`cp /home/default /etc/nginx/sites-available/default && cp /home/default /etc/nginx/sites-enabled/default && service nginx reload
`
